#!/bin/bash

#make package/feeds/uralm1/perl-devel-checklib/compile V=s
#make package/feeds/uralm1/perl-sys-runalone/compile V=s

#make package/feeds/uralm1/perl-netaddr-ip/clean
#make package/feeds/uralm1/perl-netaddr-ip/configure V=s
#make package/feeds/uralm1/perl-netaddr-ip/compile V=s

#make package/feeds/uralm1/perl-dbi/clean
#make package/feeds/uralm1/perl-dbi/prepare
#make package/feeds/uralm1/perl-dbi/configure V=s
#make package/feeds/uralm1/perl-dbi/compile V=s
#make package/feeds/uralm1/perl-dbi/host/compile V=s

#make package/feeds/uralm1/perl-dbd-mysql/clean
#make package/feeds/uralm1/perl-dbd-mysql/prepare
#make package/feeds/uralm1/perl-dbd-mysql/compile V=s

#make package/feeds/uralm1/perl-mojolicious/clean
#make package/feeds/uralm1/perl-mojolicious/configure V=s
#make package/feeds/uralm1/perl-mojolicious/compile V=s

#make package/feeds/uralm1/perl-cpanel-json-xs/clean
#make package/feeds/uralm1/perl-cpanel-json-xs/configure V=s
#make package/feeds/uralm1/perl-cpanel-json-xs/compile V=s

#make package/feeds/uralm1/perl-canary-stability/compile V=s
#make package/feeds/uralm1/perl-canary-stability/host/compile V=s

#make package/feeds/uralm1/perl-common-sense/compile V=s

#make package/feeds/uralm1/perl-ev/clean
#make package/feeds/uralm1/perl-ev/configure V=s
#make package/feeds/uralm1/perl-ev/compile V=s

#make package/feeds/uralm1/perl-net-ssleay/clean
#make package/feeds/uralm1/perl-net-ssleay/configure V=s
#make package/feeds/uralm1/perl-net-ssleay/compile V=s

#make package/feeds/uralm1/perl-io-socket-ssl/clean
#make package/feeds/uralm1/perl-io-socket-ssl/prepare
#make package/feeds/uralm1/perl-io-socket-ssl/configure V=s
#make package/feeds/uralm1/perl-io-socket-ssl/compile V=s

#make package/feeds/uralm1/perl-minion/clean
#make package/feeds/uralm1/perl-minion/prepare
#make package/feeds/uralm1/perl-minion/configure V=s
#make package/feeds/uralm1/perl-minion/compile V=s

#make package/feeds/uralm1/perl-minion-backend-mysql/clean
#make package/feeds/uralm1/perl-minion-backend-mysql/prepare
#make package/feeds/uralm1/perl-minion-backend-mysql/configure V=s
#make package/feeds/uralm1/perl-minion-backend-mysql/compile V=s

#make package/feeds/uralm1/perl-minion-backend-sqlite/clean
#make package/feeds/uralm1/perl-minion-backend-sqlite/prepare
#make package/feeds/uralm1/perl-minion-backend-sqlite/compile V=s

#make package/feeds/uralm1/perl-dbd-sqlite/clean
#make package/feeds/uralm1/perl-dbd-sqlite/prepare
#make package/feeds/uralm1/perl-dbd-sqlite/configure V=s
#make package/feeds/uralm1/perl-dbd-sqlite/compile V=s

#make package/feeds/uralm1/perl-sql-abstract/clean
#make package/feeds/uralm1/perl-sql-abstract/prepare
#make package/feeds/uralm1/perl-sql-abstract/configure V=s
#make package/feeds/uralm1/perl-sql-abstract/compile V=s

#make package/feeds/uralm1/perl-mojo-mysql/clean
#make package/feeds/uralm1/perl-mojo-mysql/prepare
#make package/feeds/uralm1/perl-mojo-mysql/configure V=s
#make package/feeds/uralm1/perl-mojo-mysql/compile V=s

#make package/feeds/uralm1/perl-mojo-sqlite/clean
#make package/feeds/uralm1/perl-mojo-sqlite/prepare
#make package/feeds/uralm1/perl-mojo-sqlite/compile V=s

#make package/feeds/uralm1/perl-try-tiny/clean
#make package/feeds/uralm1/perl-try-tiny/prepare
#make package/feeds/uralm1/perl-try-tiny/configure V=s
#make package/feeds/uralm1/perl-try-tiny/compile V=s

#make package/feeds/uralm1/perl-sub-quote/clean
#make package/feeds/uralm1/perl-sub-quote/prepare
#make package/feeds/uralm1/perl-sub-quote/configure V=s
#make package/feeds/uralm1/perl-sub-quote/compile V=s

#make package/feeds/uralm1/perl-role-tiny/clean
#make package/feeds/uralm1/perl-role-tiny/prepare
#make package/feeds/uralm1/perl-role-tiny/configure V=s
#make package/feeds/uralm1/perl-role-tiny/compile V=s

#make package/feeds/uralm1/perl-hash-merge/clean
#make package/feeds/uralm1/perl-hash-merge/prepare
#make package/feeds/uralm1/perl-hash-merge/configure V=s
#make package/feeds/uralm1/perl-hash-merge/compile V=s

#make package/feeds/uralm1/perl-clone/clean
#make package/feeds/uralm1/perl-clone/prepare
#make package/feeds/uralm1/perl-clone/configure V=s
#make package/feeds/uralm1/perl-clone/compile V=s

#make package/feeds/uralm1/perl-clone-choose/clean
#make package/feeds/uralm1/perl-clone-choose/prepare
#make package/feeds/uralm1/perl-clone-choose/configure V=s
#make package/feeds/uralm1/perl-clone-choose/compile V=s

#make package/feeds/uralm1/perl-moo/clean
#make package/feeds/uralm1/perl-moo/prepare
#make package/feeds/uralm1/perl-moo/configure V=s
#make package/feeds/uralm1/perl-moo/compile V=s

#make package/feeds/uralm1/perl-uri-db/clean
#make package/feeds/uralm1/perl-uri-db/prepare
#make package/feeds/uralm1/perl-uri-db/configure V=s
#make package/feeds/uralm1/perl-uri-db/compile V=s

#make package/feeds/uralm1/perl-uri-nested/clean
#make package/feeds/uralm1/perl-uri-nested/prepare
#make package/feeds/uralm1/perl-uri-nested/configure V=s
#make package/feeds/uralm1/perl-uri-nested/compile V=s

#make package/feeds/uralm1/perl-time-timegm/clean
#make package/feeds/uralm1/perl-time-timegm/prepare
#make package/feeds/uralm1/perl-time-timegm/configure V=s
#make package/feeds/uralm1/perl-time-timegm/compile V=s

#make package/feeds/uralm1/perl-algorithm-cron/clean
#make package/feeds/uralm1/perl-algorithm-cron/prepare
#make package/feeds/uralm1/perl-algorithm-cron/configure V=s
#make package/feeds/uralm1/perl-algorithm-cron/compile V=s

